import { Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { AuthExplorer, AuthFlow, AuthLesson } from "../components/common/AuthLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

const cases = { none: { label: "No token", title: "401 Authentication required", steps: ["Request has no Authorization header", "Middleware cannot extract a Bearer token", "Middleware sends a 401 response"], result: "Authentication required", error: true }, valid: { label: "Valid token", title: "Verified request", steps: ["Bearer token is extracted", "JWT signature and expiration are verified", "User identity attaches to req.user", "Middleware calls next()"] }, invalid: { label: "Invalid token", title: "401 Invalid token", steps: ["Bearer token is extracted", "Verification fails", "Middleware sends a 401 response"], result: "Invalid or expired token", error: true }, expired: { label: "Expired token", title: "401 Expired token", steps: ["Bearer token is extracted", "Expiration check fails", "Middleware sends a 401 response"], result: "Invalid or expired token", error: true } };

function AuthMiddlewareLesson() {
  const learn = <Stack spacing={2}><SectionCard title="Authenticate requests"><Typography color="text.secondary">Auth middleware reads the Authorization header, extracts a Bearer token, verifies it, attaches the user identity to <code>req.user</code>, then calls <code>next()</code>. Missing or invalid credentials should produce a 401 response.</Typography></SectionCard><SectionCard title="Finish or continue"><Typography color="text.secondary">Middleware calls <code>next()</code> only when the request should continue. On failure, it finishes the response. Later authorization middleware can decide whether an authenticated user has permission.</Typography></SectionCard></Stack>;
  const code = <SectionCard title="Conceptual authentication middleware"><CodeBlock filename="middleware/authenticate.js">{"function authenticate(req, res, next) {\n  const token = extractBearerToken(req);\n\n  if (!token) {\n    return res.status(401).json({\n      success: false,\n      message: \"Authentication required\"\n    });\n  }\n\n  try {\n    req.user = jwt.verify(token, process.env.JWT_SECRET);\n    next();\n  } catch {\n    return res.status(401).json({\n      success: false,\n      message: \"Invalid or expired token\"\n    });\n  }\n}"}</CodeBlock></SectionCard>;
  return <AuthLesson lesson="25" title="Auth Middleware" subtitle="Learn how middleware verifies tokens before a protected controller runs." learn={learn} code={code} tryIt={<AuthExplorer title="Auth Middleware Explorer" subtitle="Conceptual cases only; no real tokens are stored or verified." options={cases} />} flow={<AuthFlow title="Protected request flow" steps={["Request", "Authorization header", "Auth middleware", "Extract Bearer token", "Verify", "Attach user identity", "next()"]} />} />;
}

export default AuthMiddlewareLesson;