import { Box, Grid, Stack, Typography } from "@mui/material";
import { ProductionExplorer, ProductionFlow, ProductionLesson } from "../components/common/ProductionLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

const architectures = { local: { label: "Local Development", title: "Local development", steps: ["React development server", "Node backend runs locally", "Local configuration supports development"] }, single: { label: "Single Server", title: "Single production deployment", steps: ["Frontend build is hosted as static files", "Node backend serves API traffic", "HTTPS and health checks support operation"] }, scaled: { label: "Scaled Production", title: "Scaled production", steps: ["CDN or static hosting serves frontend", "Reverse proxy or load balancer routes traffic", "Multiple backend instances can scale", "Health checks guide traffic"] } };

function DeploymentLesson() {
  const learn = <Stack spacing={2}><SectionCard title="From development to production"><Typography color="text.secondary">A frontend build produces static assets that can use static hosting or a CDN. The Node backend deploys separately to handle API traffic. Production requires HTTPS, environment configuration, and health checks.</Typography></SectionCard><SectionCard title="Delivery and scaling"><Typography color="text.secondary">CI/CD can build, test, and deploy changes consistently. A reverse proxy, load balancer, or containers can be useful, but none is mandatory for every application. Scaling choices depend on measured traffic and operational needs.</Typography></SectionCard><SectionCard title="Graceful operations"><Typography color="text.secondary">A production backend should stop accepting new work during graceful shutdown, finish active work where possible, and let infrastructure health checks direct traffic away from unhealthy instances.</Typography></SectionCard></Stack>;
  const code = <SectionCard title="Full-stack architecture"><Box component="pre" sx={{ m: 0, p: 2, borderRadius: 2, color: "#e2e8f0", backgroundColor: "#0f172a", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace" }}>{"React\n  → API\n  → Express\n  → Middleware\n  → Controller\n  → Service\n  → Repository\n  → MySQL"}</Box></SectionCard>;
  return <ProductionLesson lesson="35" title="Deployment Architecture" subtitle="Learn how frontend, backend, configuration, and infrastructure fit together in production." learn={learn} code={code} tryIt={<ProductionExplorer title="Architecture Selector" subtitle="Compare common deployment shapes conceptually." options={architectures} />} flow={<Stack spacing={2}><ProductionFlow title="Delivery flow" steps={["Developer", "Git", "CI/CD", "Build and test", "Deploy", "Health check", "Traffic"]} /><ProductionFlow title="Full-stack request flow" steps={["React", "API", "Express", "Middleware", "Controller", "Service", "Repository", "MySQL"]} /></Stack>} />;
}

export default DeploymentLesson;