import { Box, Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { ConceptExplorer, CoreLesson, FlowCards } from "../components/common/CoreLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

const operations = { read: { label: "Read File", title: "Read file", steps: ["Node fs API receives the read request", "File system retrieves content", "Promise resolves with text or rejects with an error"], result: "Conceptual result: file content returned." }, write: { label: "Write File", title: "Write file", steps: ["Node fs API receives content", "File system writes the target file", "Promise resolves or rejects with an error"], result: "Conceptual result: file written." }, append: { label: "Append File", title: "Append file", steps: ["Node fs API receives additional content", "File system appends data", "Promise resolves or rejects with an error"], result: "Conceptual result: content appended." } };

function FileSystemLesson() {
  const learn = <Stack spacing={2}><SectionCard title="The fs core module"><Typography color="text.secondary">Node.js provides the built-in <Box component="code">fs</Box> module for working with files. Common operations include reading, writing, appending, and checking accessibility or existence.</Typography></SectionCard><SectionCard title="Synchronous vs asynchronous"><Typography color="text.secondary"><Box component="code">readFileSync</Box> blocks JavaScript while it waits. <Box component="code">readFile</Box> schedules the operation and returns a Promise, which is generally preferred in servers so other work can continue. Async work can still fail, so handle errors intentionally.</Typography></SectionCard></Stack>;
  const code = <Stack spacing={2}><SectionCard title="Promise-based file operations"><CodeBlock filename="file-service.js">{"import { readFile, writeFile } from \"node:fs/promises\";\n\nconst content = await readFile(\"./data.txt\", \"utf8\");\nawait writeFile(\"./output.txt\", content);"}</CodeBlock></SectionCard><SectionCard title="Core operations"><Typography color="text.secondary"><Box component="code">readFile</Box> reads content, <Box component="code">writeFile</Box> creates or replaces it, and <Box component="code">appendFile</Box> adds content. Use access or existence checks carefully and still handle an operation’s possible error.</Typography></SectionCard></Stack>;
  return <CoreLesson lesson="08" title="File System" subtitle="Learn how Node.js reads and writes files using the built-in fs module." learn={learn} code={code} tryIt={<ConceptExplorer title="Conceptual File Operation Explorer" subtitle="Explore operations without accessing real local files from React." options={operations} />} flow={<Stack spacing={2}><FlowCards flows={[{ title: "File operation flow", steps: ["React learning UI", "Node fs API concept", "File operation", "Filesystem", "Result or error"] }]} /><Typography variant="body2" color="text.secondary">Real file-system backend demos can be introduced later if needed.</Typography></Stack>} />;
}

export default FileSystemLesson;