import { Box, Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { DatabaseExplorer, DatabaseFlow, DatabaseLesson } from "../components/common/DatabaseLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

const migration = { structure: { label: "Architecture", title: "MySQL-backed task flow", steps: ["Route matches /api/tasks", "Controller handles req and res", "Service validates title and not-found rules", "Repository executes parameterized SQL", "MySQL persists the task", "Compatible JSON response returns"] }, requirement: { label: "Requirement", title: "mysql2 is required", steps: ["The current server manifest does not declare mysql2", "No dependency was installed for this phase", "The existing task API remains temporary in-memory data", "Install and configure mysql2 in a dedicated setup phase before wiring persistence"] } };

function MySqlCrud() {
  const learn = <Stack spacing={2}><SectionCard title="From in-memory to persistent CRUD"><Typography color="text.secondary">The current task API uses temporary in-memory data, which resets on server restart. A MySQL-backed version would retain data in a <Box component="code">tasks</Box> table and preserve the existing client response shapes where possible.</Typography></SectionCard><SectionCard title="Dependency required"><Typography color="text.secondary">Real persistence is not wired in this phase because <Box component="code">mysql2</Box> is not installed in the server project. The intended files are shown here as code structure only; no persistence is simulated.</Typography></SectionCard></Stack>;
  const code = <Stack spacing={2}><SectionCard title="Table concept"><CodeBlock filename="schema.sql">{"CREATE TABLE tasks (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  title VARCHAR(255) NOT NULL,\n  completed BOOLEAN NOT NULL DEFAULT FALSE,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);"}</CodeBlock></SectionCard><SectionCard title="Planned backend structure"><CodeBlock filename="server/src">{"config/database.js\nrepositories/taskRepository.js\nservices/taskService.js\nroutes/taskRoutes.js\ncontrollers/taskController.js"}</CodeBlock><Typography variant="body2" color="text.secondary" sx={{ mt: 1.5 }}>Repository methods would be findAll, findById, create, update, patch, and delete, each using parameterized queries. The service would own title validation and not-found rules; the controller would own req/res and status codes.</Typography></SectionCard></Stack>;
  return <DatabaseLesson lesson="22" title="Persistent CRUD" subtitle="Understand the migration from temporary task data to MySQL-backed CRUD." learn={learn} code={code} tryIt={<DatabaseExplorer title="Persistent CRUD Migration" subtitle="This is a conceptual architecture view. The existing REST playground remains backed by temporary in-memory data." options={migration} />} flow={<Stack spacing={2}><DatabaseFlow title="Persistence path" steps={["React", "Axios", "Express", "Service", "Repository", "MySQL"]} /><Typography variant="body2" color="text.secondary">Database failures should eventually map to safe 500 responses without exposing SQL, credentials, or stack traces.</Typography></Stack>} />;
}

export default MySqlCrud;