import { Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { DatabaseExplorer, DatabaseFlow, DatabaseLesson } from "../components/common/DatabaseLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

const queries = { select: { label: "SELECT", title: "Find a task", steps: ["SQL uses WHERE id = ?", "Parameter array supplies the task ID", "Repository returns a task or no result"], result: "SQL: SELECT id, title, completed\nFROM tasks\nWHERE id = ?\n\nParameters: [10]" }, insert: { label: "INSERT", title: "Create a task", steps: ["SQL has placeholders", "Parameters provide title and completed", "Database creates a new row"], result: "SQL: INSERT INTO tasks (title, completed)\nVALUES (?, ?)\n\nParameters: [\"Learn MySQL\", false]" }, update: { label: "UPDATE", title: "Update a task", steps: ["SQL identifies a row with WHERE id = ?", "Parameters keep data separate from SQL", "Database updates the row"], result: "SQL: UPDATE tasks\nSET title = ?, completed = ?\nWHERE id = ?\n\nParameters: [\"Learn MySQL\", true, 10]" }, delete: { label: "DELETE", title: "Delete a task", steps: ["SQL identifies a row with WHERE id = ?", "Parameter supplies the task ID", "Database removes the row"], result: "SQL: DELETE FROM tasks\nWHERE id = ?\n\nParameters: [10]" } };

function MySqlQueries() {
  const learn = <Stack spacing={2}><SectionCard title="CRUD queries"><Typography color="text.secondary">SQL uses SELECT to read, INSERT to create, UPDATE to change, and DELETE to remove. WHERE narrows an operation to matching rows.</Typography></SectionCard><SectionCard title="Parameterized queries"><Typography color="text.secondary">Use <strong>?</strong> placeholders and pass values separately. This helps prevent SQL injection by avoiding dynamic value concatenation, but it does not remove every security concern.</Typography></SectionCard><SectionCard title="Repository responsibility"><Typography color="text.secondary">A repository owns SQL and data access. A TaskRepository can expose <strong>findAll()</strong>, <strong>findById(id)</strong>, <strong>create(task)</strong>, <strong>update(id, task)</strong>, and <strong>delete(id)</strong> without exposing SQL details to controllers.</Typography></SectionCard></Stack>;
  const code = <SectionCard title="Parameterized CRUD"><CodeBlock filename="taskRepository.js">{"SELECT id, title, completed\nFROM tasks\nWHERE id = ?\n\nINSERT INTO tasks (title, completed)\nVALUES (?, ?)\n\nUPDATE tasks\nSET title = ?, completed = ?\nWHERE id = ?\n\nDELETE FROM tasks\nWHERE id = ?"}</CodeBlock></SectionCard>;
  return <DatabaseLesson lesson="20" title="Queries & Repository" subtitle="Learn how repositories use parameterized SQL for MySQL CRUD operations." learn={learn} code={code} tryIt={<DatabaseExplorer title="SQL Explorer" subtitle="Choose a predefined CRUD query and inspect SQL separately from its parameters." options={queries} />} flow={<DatabaseFlow title="Database request flow" steps={["Controller", "Service", "Repository", "MySQL"]} />} />;
}

export default MySqlQueries;