import { Box, Grid, Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { AdvancedExplorer, AdvancedFlow, AdvancedLesson } from "../components/common/AdvancedLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

function PerformanceMemoryLesson() {
  const learn = <Stack spacing={2}><SectionCard title="Measure before optimizing"><Typography color="text.secondary">Performance work starts with measurement. CPU-heavy tasks can block the main thread, while memory usage includes a stack, heap, external allocations, and process overhead. High memory use alone does not automatically prove a leak.</Typography></SectionCard><SectionCard title="Memory and garbage collection"><Typography color="text.secondary">At a high level, <Box component="code">rss</Box> is process memory, <Box component="code">heapTotal</Box> and <Box component="code">heapUsed</Box> describe JavaScript heap allocation, and <Box component="code">external</Box> tracks memory managed outside the heap. Garbage collection reclaims unreachable memory but cannot prevent all leaks, such as unbounded caches or retained listeners.</Typography></SectionCard><SectionCard title="Performance checklist"><Box component="ul" sx={{ my: 0, pl: 2.5, color: "text.secondary" }}><li>Avoid unnecessary blocking.</li><li>Use streams for appropriate large-data workloads.</li><li>Measure before optimizing.</li><li>Release resources and listeners.</li><li>Watch unbounded caches and collections.</li></Box></SectionCard></Stack>;
  const code = <Stack spacing={2}><SectionCard title="Memory usage"><CodeBlock filename="memory.js">{"console.log(process.memoryUsage());"}</CodeBlock></SectionCard><SectionCard title="Timing work"><CodeBlock filename="performance.js">{"import { performance } from \"node:perf_hooks\";\n\nconst start = performance.now();\n\n// work\n\nconst end = performance.now();\n\nconsole.log(`${end - start} ms`);"}</CodeBlock></SectionCard></Stack>;
  return <AdvancedLesson lesson="31" title="Performance & Memory" subtitle="Learn how to measure CPU, memory, I/O, and bottlenecks before optimizing." learn={learn} code={code} tryIt={<AdvancedExplorer title="Conceptual Performance Inspector" subtitle="Values here are categories, not real measurements." options={{ execution: { label: "Execution Time", title: "Execution time", steps: ["Measure work with performance.now", "Compare before and after", "Find the bottleneck before changing code"] }, heap: { label: "Heap Used", title: "Heap usage", steps: ["Inspect process.memoryUsage", "Watch growth over time", "Investigate retained objects"] }, process: { label: "Process Memory", title: "Process memory", steps: ["Review rss and external memory", "Consider native allocations", "Do not assume a leak from one value"] } }} />} flow={<AdvancedFlow title="Performance workflow" steps={["Application", "CPU", "Memory", "I/O", "Measurement", "Identify bottleneck", "Optimize", "Measure again"]} />} />;
}

export default PerformanceMemoryLesson;