import { Box, Stack, Typography } from "@mui/material";
import CodeBlock from "../components/common/CodeBlock.jsx";
import { ConceptExplorer } from "../components/common/CoreLesson.jsx";
import { ExpressFlow, ExpressLesson } from "../components/common/ExpressLesson.jsx";
import SectionCard from "../components/common/SectionCard.jsx";

function ValidationErrors() {
  const learn = <Stack spacing={2}><SectionCard title="Validate incoming data"><Typography color="text.secondary">Validation rejects incomplete or invalid input before it causes incorrect behavior. Missing or malformed client input often returns <Box component="code">400 Bad Request</Box>; an unknown resource returns <Box component="code">404 Not Found</Box>. Unexpected server failures may require <Box component="code">500</Box>.</Typography></SectionCard><SectionCard title="Handle failures intentionally"><Typography color="text.secondary">Controllers can return expected validation responses directly. A centralized error handler using <Box component="code">next(error)</Box> can provide a consistent unexpected-error shape without exposing stack traces. Logging alone should not silently swallow an error.</Typography></SectionCard></Stack>;
  const code = <Stack spacing={2}><SectionCard title="Manual validation"><CodeBlock filename="taskController.js">{"if (!title?.trim()) {\n  return res.status(400).json({\n    success: false,\n    message: \"Title is required\"\n  });\n}"}</CodeBlock></SectionCard><SectionCard title="Centralized error concept"><CodeBlock filename="app.js">{"app.use(errorHandler);"}</CodeBlock></SectionCard></Stack>;
  return <ExpressLesson lesson="18" title="Validation & Error Handling" subtitle="Learn how APIs return intentional validation and error responses." learn={learn} code={code} tryIt={<ConceptExplorer title="Validation Explorer" subtitle="Choose a predefined request outcome." options={{ valid: { label: "Valid task", title: "201 Created", steps: ["Request reaches validation", "Title is present", "Controller creates the task"] }, missing: { label: "Missing title", title: "400 Bad Request", steps: ["Request reaches validation", "Title is blank or missing", "Response: Title is required"] }, missingId: { label: "Unknown ID", title: "404 Not Found", steps: ["Controller looks for the task", "Task is not found", "Response: Task not found"] } }} />} flow={<Stack spacing={2}><ExpressFlow title="Success path" steps={["Request", "Validation", "Controller", "Success"]} /><ExpressFlow title="Error path" steps={["Request", "Validation or error", "Error response"]} /><Typography variant="body2" color="text.secondary">Unhandled errors can terminate or destabilize server processes depending on context; applications should handle failures intentionally.</Typography></Stack>} />;
}

export default ValidationErrors;